#!/bin/bash
echo "Starting emulator '$AVD_NAME'"
"$ANDROID_HOME/emulator/emulator64-x86" -avd "$AVD_NAME" -cores 4 -memory 4096 -no-boot-anim -no-window -no-audio -no-snapshot-save -qemu -smp 4 -m 4095 -enable-kvm
